webtalk_init -webtalk_dir D:/vivadoproject/project532/ipcore/ImageProcessing/ImageProcessing.sim/sim_1/behav/xsim/xsim.dir/test_rgb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Feb  9 21:33:17 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f5409c19-ae9a-404f-899e-2a3496c4939d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ce16f2946d4d4979beb598d5dec006c0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 8945HS w/ Radeon 780M Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "260 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8664_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1111989177 -regid "" -xml D:/vivadoproject/project532/ipcore/ImageProcessing/ImageProcessing.sim/sim_1/behav/xsim/xsim.dir/test_rgb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/vivadoproject/project532/ipcore/ImageProcessing/ImageProcessing.sim/sim_1/behav/xsim/xsim.dir/test_rgb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/vivadoproject/project532/ipcore/ImageProcessing/ImageProcessing.sim/sim_1/behav/xsim/xsim.dir/test_rgb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
